version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: aml-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aml-network

volumes:
  redis_data:

networks:
  aml-network:
    driver: bridge